In [1]:
#NUMPY --> numerical python
import numpy as np# can create the nickname like 'import numpy as np'

#numpy provides the support for most powerful data structure -- array
num=np.array([10,20,30,40,50])
print(type(num))
print(num)

<class 'numpy.ndarray'>
[10 20 30 40 50]


In [2]:
# Python Numpy Vs List
numbers = [1, 2, 3, 4, 5]
total = 0
for n in numbers:
 total += n 
print(total)

15


In [3]:
numbers = np.array([1, 2, 3, 4, 5])
print(np.sum(numbers))

15


In [4]:
# how much execution time will it take
import time
numbers = list(range(1, 10000))  # 1 2 3 4 5..................9999
n=0
start_time = time.time() # record start time
for i in numbers:
 n += i
end_time = time.time() # record end time
print("Total:", n)
print("Execution Time:", end_time - start_time, "seconds") 
print(f"Execution Time: {end_time - start_time:.4f} seconds") # .4f → means “show 4 digits after the decimal point.

Total: 49995000
Execution Time: 0.003961324691772461 seconds
Execution Time: 0.0040 seconds


In [5]:
numbers = np.arange(1, 10000000)
start_time = time.time()
total = np.sum(numbers)
end_time = time.time()
print("Total:", total)
print(f"Execution Time: {end_time - start_time:.4f} seconds")

Total: 49999995000000
Execution Time: 0.0071 seconds


In [6]:
# Array
# In programming, an array is a data structure used to store a collection of elements,
# or values, of the same data type under a single variable name.

# array have : single dimensional (1D) and multi dimensional (2D)
# "array ()" used to create 1D and 2D

num=np.array([10,20,30,40,50])
print(num)
print(type(num))

[10 20 30 40 50]
<class 'numpy.ndarray'>


In [7]:
# shape property
# used to determine the dimensions of an array
# For 1D array return (n,)    --> where n is the number of elements
# For 2D array return (n,m)   --> where n is the number of row and m is the number of column
print(num.shape)

(5,)


In [8]:
# create a 2D array
import numpy as np
num = np.array([[1,2],[3,4],[5,6]])
print(num)
print(num.shape)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)


In [9]:
#3x4
num = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(num)

#5x2
num1= np.array([[1,2],[3,4],[5,6],[7,8],[9,10]])
print(num1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [10]:
#indexing and slicing
print(num[0])
print(num1[4])
print(num[2:2:1])
print(num1[1:2])
print(num1[::-1])


[1 2 3 4]
[ 9 10]
[]
[[3 4]]
[[ 9 10]
 [ 7  8]
 [ 5  6]
 [ 3  4]
 [ 1  2]]


In [11]:
arr = np.array([10,20,30,40,50,60,70,80,90])

print(arr)
 
# Indexing and Slicing

print(arr[2])
print(arr[-1])
print(arr[2:7])
print(arr[::-1])
print(arr[2:7:2])

[10 20 30 40 50 60 70 80 90]
30
90
[30 40 50 60 70]
[90 80 70 60 50 40 30 20 10]
[30 50 70]


In [12]:
num = np.array([[1,2],[3,4],[5,6]])
print(num)
print(num[0,1])   #[row,coloum]
print(num[1])

#show 1st row
print(num[0])
#show 2nd coloum
print(num[:,1])
# show last row
print(num[2,:])
#show first 2 rows
print(num[0:2,0])

[[1 2]
 [3 4]
 [5 6]]
2
[3 4]
[1 2]
[2 4 6]
[5 6]
[1 3]


In [13]:
# Numpy Data types (numpy can't mix, str also cnnot)
num=np.array([10,20,30,40])
print(num.dtype) # 'dtype' property helps us to determine the data type of an array

int64


In [14]:
num=np.array([10.12,20.4,30.60,40])
print(num.dtype)

float64


In [15]:
num=np.array([True,False,False])
print(num.dtype)

bool


In [16]:
num=np.array(['apple so good','banana so sweet'])
print(num.dtype)

# <U --> unicode string
# 15 --> max lenght of a string

<U15


In [17]:
# using dtype for conversion
num=np.array([1,2,3,4,5],dtype='f2')
print(num.dtype)

float16


In [18]:
# astype() used for conversion
num=np.array([1,2,3,4,5])
num = num.astype('f2')
print(num.dtype)

float16


In [19]:
# numpy copy() vs view()
# copy()
# a copy will create a new independent array in a different memory location
 
org_arr = np.array([1,2,3,4,5])
copied_arr = org_arr.copy()
print(copied_arr)
 
# if you make changes in copied_arr , it won't affect the original array
 
copied_arr[0] = 100
print(copied_arr)
print(org_arr)
 
# if you make changes in org_arr , it won't affect the copied array
 
org_arr[2] = 300
print(org_arr)
print(copied_arr)

[1 2 3 4 5]
[100   2   3   4   5]
[1 2 3 4 5]
[  1   2 300   4   5]
[100   2   3   4   5]


In [20]:
num=np.array([1,2,3,4,5]) #1 create copy of the original
num1=num.copy()
print(num1)

num1 [0]= 100 # if make changes in copy(num1), it don't effect the original(num)
print(num1)
print(num)

num[2] = 300 # if you change in original(num), it won't effect the copy array(num1)
print(num)
print(num1)

[1 2 3 4 5]
[100   2   3   4   5]
[1 2 3 4 5]
[  1   2 300   4   5]
[100   2   3   4   5]


In [21]:
# view()
# a view is the representation of the original array
# it shares the same memory location
 
org_arr = np.array([1,2,3,4,5])
copied_arr = org_arr.view()
print(copied_arr)
 
# if you make changes in copied_arr , it will affect the original array
copied_arr[0] = 100
print(copied_arr)
print(org_arr)
 
# if you make changes in org_arr , it will affect the copied array
 
org_arr[2] = 300
print(org_arr)
print(copied_arr)

[1 2 3 4 5]
[100   2   3   4   5]
[100   2   3   4   5]
[100   2 300   4   5]
[100   2 300   4   5]


In [22]:
# Numpy array reshaping --> converting 1D into 2D or 2D into 1D
#reshape()

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr.shape)   # 2x6  6x2  3x4  4x3  12x1  1x12
 
twod = arr.reshape(3,4)
print(twod)
 
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13])   # 1x13  13x1
twod = arr.reshape(13,1)
print(twod)
 

(12,)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]]


In [23]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13])
# numpy.newaxis
# is used to increase the dimension of the existing array by one more dimension meaning
# 1D array will become 2D array
arr[:,np.newaxis]  # Column vector

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13]])

In [24]:
arr= np.array([1,2,3,4,5,6,7,8,9,10])
arr[np.newaxis,:] # row vector

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [25]:
#convert 2D to 1D
twod= np.array([[1,2],[3,4],[5,6]])
print(twod.shape)

ar=twod.reshape(6)
print(ar)

(3, 2)
[1 2 3 4 5 6]


In [26]:
twod= np.array([[1,2],[3,4],[5,6]])
print(twod.shape)

ar=twod.reshape(-1) # if don't know the shape can use '-1' instead
print(ar)

(3, 2)
[1 2 3 4 5 6]


In [27]:
twod= np.array([[1,2],[3,4],[5,6]])
print(twod.shape)

ar=twod.flatten()  # also can use .flatten() much more easier
print(ar)

(3, 2)
[1 2 3 4 5 6]


In [28]:
#concatenate (mengabungkan)
# used to merge 2 array

num1= np.array ([1,2,3,4])
num2= np.array([5,6,7,8])
num = np.concatenate((num1,num2))
print(num)

[1 2 3 4 5 6 7 8]


In [29]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8],[9,10]])
arr = np.concatenate((arr1,arr2))
print(arr)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [30]:
num1 = np.array([[1,2],[3,4]])
num2 = np.array([[5,6],[7,8],[9,10]])
num = np.concatenate((num1,num2))
print(num)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [31]:
# array_split()
num = np.array([1,2,3,4,5,6,7,8,9,10])
np.array_split(num,3)

[array([1, 2, 3, 4]), array([5, 6, 7]), array([ 8,  9, 10])]

In [32]:
# sorting
prices= np.array([50,67,98,23,56,12,55,99])
print(np.sort(prices)[::-1])  # use for reverse/descending

[99 98 67 56 55 50 23 12]


In [33]:
#flitering and searching inn array
num=np.array([1,3,7,3,5,9,6,2,10])
print(num)

for i in num:
    if i>=5:
        print(i)
        

[ 1  3  7  3  5  9  6  2 10]
7
5
9
6
10


In [34]:
# Boolean masking
res=num>=5
print(res)

[False False  True False  True  True  True False  True]


In [35]:
num=np.array([1,3,7,3,5,9,6,2,10])
num1 = num [num>=5]
print(num1)

[ 7  5  9  6 10]


In [36]:
# np.where (exprsn)
# np.where return index number(shows output of index)

num=np.array([1,3,7,3,5,9,6,2,10])
res=np.where(num>=5)
print(res)

(array([2, 4, 5, 6, 8]),)


In [37]:
arr = np.array([10, 32, 30, 50, 20, 82, 91, 45])
 
# Find indices where value is 30
indices = np.where(arr == 30)
print(f"Indices where value is 30: {indices}")
 
# Find indices where values are even
even_indices = np.where(arr % 2 == 0)
print(f"Indices of even values: {even_indices}")
 
# Conditional selection
new_arr = np.where(arr > 40, arr * 2, arr)
print(f"Array after conditional selection: {new_arr}")

Indices where value is 30: (array([2]),)
Indices of even values: (array([0, 1, 2, 3, 4, 5]),)
Array after conditional selection: [ 10  32  30 100  20 164 182  90]


In [38]:
# Numpy random module
from numpy import random
x=random.randint(100)   #1 -->100
print(x)

53


In [39]:
x=random.randint(100,150)
print(x)

106


In [40]:
# rand() method return random float value b/w 0 and 1
# generate random float

print(random.rand())

0.027732451202506447


In [41]:
# generating random 1D array
x=random.randint(30,70,size=(5))
print(x)

[54 68 69 52 31]


In [42]:
# generating random 2D array
x=random.randint(30,70,size=(3,4))
print(x)

[[37 31 49 58]
 [43 43 38 64]
 [61 38 45 42]]


In [43]:
x= random.randint(100,size=(3,4))
print(x)

[[19 36 16 71]
 [79 30 95  9]
 [35 37  1 85]]


In [44]:
x= random.rand(8)
print(x)

[0.93650434 0.04475536 0.33555765 0.30831615 0.64533192 0.3734092
 0.64886832 0.09264829]


In [45]:
x=random.rand(3,5)
print(x)

[[6.34924129e-01 9.42355717e-03 1.57364811e-01 4.74873009e-01
  1.73931355e-01]
 [2.64848884e-03 2.19337337e-01 3.71807202e-02 9.53166850e-01
  1.78808139e-01]
 [1.36505294e-01 4.95709484e-01 1.06847017e-04 3.82698422e-01
  6.22459615e-02]]


In [46]:
# the choice() method allows you to generate a random value
# based on an array of values.
x=random.choice([3,4,5,6])
print(x)

3


In [47]:
x= random.choice([3,5,7,9], size=(12))
print(x)

[7 5 5 5 3 5 3 5 3 5 3 7]


In [48]:
x=random.choice([6,7,8,9],size=(3,4))
print(x)

[[8 6 7 9]
 [6 7 8 8]
 [9 7 7 8]]


In [49]:
# numpy.zeroes()
# this function allows us to create an array filled with zero's
# default data type will be FLOAT

num= np.zeros(12)
print(num)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [50]:
num= np.zeros((3,5)) # alert with the bracket
print(num)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [51]:
num= np.ones(12)
print(num)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [52]:
#numpy.sum()
#used to compute teh sum of all elements
x=np.random.randint(54, size=12)
print(x)
print(np.sum(x))

[29 21  4 26 29 41  3 10 47  5 30 22]
267


In [53]:
#numpy.mean()
#mean value is the average value 
print(np.mean(x))   #formula sum of value/number of value

22.25


In [54]:
# numpy.mode
# the mode value is the value that appears most
from scipy import stats
print(stats.mode(x))

ModeResult(mode=np.int32(29), count=np.int64(2))


In [55]:
#numpy.unique()
# return unique element as a sorted array
a=np.unique([1,2,3,4,2,3,4,5,8,6,5,4,3,9,8,7,4,3,3,5,6])
print(a)

[1 2 3 4 5 6 7 8 9]


In [56]:
arr = np.array([1,2,3,4,1,2,1,1,1,5,6,7,5,9,10,11,8,6,5])

# 1 2 3 4 5 6 7 9 10 11 8

uv , i = np.unique(arr,return_index=True)
print(uv,i)
 
# return_index=True gives you 2 things
# a.) unique value   -->  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11
# b.) index numbers   --> 0,  1,  2,  3,  9, 10, 11, 16, 13, 14, 15
#     first occurence
 
# argsort --> reorder based on original appearance
uv[np.argsort(i)]

[ 1  2  3  4  5  6  7  8  9 10 11] [ 0  1  2  3  9 10 11 16 13 14 15]


array([ 1,  2,  3,  4,  5,  6,  7,  9, 10, 11,  8])

In [57]:
#arange() #same as range()
print(np.arange(11))
print(np.arange(1,11))
print(np.arange(1,11,3))

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]
[ 1  4  7 10]


In [58]:
print(np.arange(4).reshape(2,2))

[[0 1]
 [2 3]]


In [59]:
# numpy broadcasting
arr1 = np.array([4,5,7,8])
arr2 = np.array([8,1,3,4])
print(arr1 + arr2)

[12  6 10 12]


In [61]:
# if we try to perform arithmetic operation 
# b/w uncompatible shapes
 
arr1 = np.array([4,5,7,8])
arr2 = np.array([8,1,3,4])
print(arr1 + arr2)


[12  6 10 12]


In [62]:
# if any one of them is 1 it will works too
 
arr1 = np.array([4,5,7,8])
arr2 = np.array([8])
print(arr1 + arr2)

[12 13 15 16]
